version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    command: sh -c "npm start"
    environment:
      - NODE_ENV=development
